force-app/main/default/objects/Applied_Credit__c/Applied_Credit__c.object-meta.xml
<CustomObject>
    <label>Applied Credit</label>
    <nameField>
        <displayFormat>AC-{YYYY}{000}</displayFormat>
        <label>Applied Credit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applied Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Applied_Credit__c/fields/Applied_Amount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Amount__c</fullName>
    <label>Applied Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Applied_Credit__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Applied Credits</relationshipLabel>
    <relationshipName>Applied_Credits</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Applied_Credit__c/fields/Credit__c.field-meta.xml
<CustomField>
    <fullName>Credit__c</fullName>
    <label>Credit</label>
    <referenceTo>Credit__c</referenceTo>
    <relationshipLabel>Applied Credits</relationshipLabel>
    <relationshipName>Applied_Credits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit__c/Credit__c.object-meta.xml
<CustomObject>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Credit_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Credit_Percentage__c</fullName>
    <label>Credit Percentage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>75</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Credits_Available__c.field-meta.xml
<CustomField>
    <fullName>Credits_Available__c</fullName>
    <formula>if(NOT(ISBLANK(Credit_Amount__c)),
    Credit_Amount__c -  Credits_Applied__c,
    null
			)</formula>
    <label>Credits Available</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credits</relationshipLabel>
    <relationshipName>Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percentage</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreditService.cls
public with sharing class CreditService {
    public static List<Credit__c> getCredits(Id contactId) {
        Contact con = [
            SELECT Id, AccountId
            FROM Contact
            WHERE Id = :contactId
        ];

        return [
            SELECT Type__c, Credit_Percentage__c, Credit_Amount__c, Credits_Available__c
            FROM Credit__c
            WHERE Household__c = :con.AccountId AND (Credits_Available__c > 0 OR Credits_Available__c = NULL)
        ];
    }

    public static void createAppliedCredits(Id cartId, String appliedCreditsJson) {
        List<AppliedCredit> appCredits = (List<AppliedCredit>) System.JSON.deserialize(appliedCreditsJson, List<AppliedCredit>.class);
        System.debug(appCredits);

        List<Credit__c> updateCredits = new List<Credit__c>();
        List<Applied_Credit__c> insertAppliedCredits = new List<Applied_Credit__c>();
        for (AppliedCredit appCredit : appCredits) {
            if (appCredit.type == 'Percentage') {
                updateCredits.add(new Credit__c(
                    Id = appCredit.id,
                    Credit_Amount__c = appCredit.value
                ));
            }

            insertAppliedCredits.add(new Applied_Credit__c(
                Cart__c = cartId,
                Credit__c = appCredit.id,
                Applied_Amount__c = appCredit.value
            ));
        }
        if (updateCredits.size() > 0) {
            update updateCredits;
        }
        if (insertAppliedCredits.size() > 0) {
            insert insertAppliedCredits; 
        }
    }

    public class AppliedCredit {
        public String id;
        public Decimal value;
        public String type;
    }
}