force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Checkout Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credit__c/Credit__c.object-meta.xml
<CustomObject>
    <label>Credit</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Credit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Credit__c/fields/Credit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Amount__c</fullName>
    <label>Credit Amount</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Credit__c/fields/Household__c.field-meta.xml
<CustomField>
    <fullName>Household__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Household</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credits</relationshipLabel>
    <relationshipName>Credits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ViewCartControllerTest.cls
@isTest
private class ViewCartControllerTest {

    @testSetup
    private static void makeData() {

        Account acc = (Account) new SObjectBuilder(Account.SObjectType)
            .create()
            .getRecord();

        Contact uContact = (Contact) new SObjectBuilder(Contact.SObjectType)
            .put(Contact.AccountId, acc.Id)
            .create()
            .getRecord(); 
        
        Cart__c cart = (Cart__c) new SObjectBuilder(Cart__c.SObjectType)
            .put(Cart__c.Status__c, 'Open')
            .create()
            .getRecord();
        
        Credit__c credit = (Credit__c) new SObjectBuilder(Credit__c.SObjectType)
            .put(Credit__c.Household__c, acc.Id)
            .put(Credit__c.Credit_Amount__c, 60)
            .create()
            .getRecord();
    }

    @isTest
    private static void getCartTest() {
        Cart__c cart = ViewCartController.getCart([SELECT Id FROM Cart__c LIMIT 1].Id);
        Assert.isNotNull(cart, 'No Cart Returned.');

        try {
            cart = ViewCartController.getCart(null);
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Returned cart with a null Id.');
        }
    }
    
    @isTest
    private static void getCreditsTest() {
        List<Credit__c> credits = ViewCartController.getCredits([SELECT Id FROM Contact LIMIT 1].Id);
        Assert.isTrue(credits.size() > 0, 'No Credits returned.');

        try {
            credits = ViewCartController.getCredits(null);
        }
        catch (Exception ex) {
            Assert.isNotNull(ex.getMessage(), 'Returned Credits with a null Id.');
        }
    }

}