force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <label>Amount Paid</label>
    <summarizedField>Invoice__c.Amount__c</summarizedField>
    <summaryForeignKey>Invoice__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Checkout Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Stripe_Subscription_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Subscription_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Subscription Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <summarizedField>Cart_Product__c.Total__c</summarizedField>
    <summaryForeignKey>Cart_Product__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{YYYY}{000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Invoice_PDF__c.field-meta.xml
<CustomField>
    <fullName>Invoice_PDF__c</fullName>
    <label>Invoice PDF</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeInvoiceCallbackClass.cls
/**
 * @Class Name     : 
 * @Class Purpose  : 
 * @Author         : Zachary Csotya
 * @Developed On   : 
 * @Last Modified  : 06/13/2024
**/
@RestResource(UrlMapping='/StripeInvoice')
global without sharing class StripeInvoiceCallbackClass {
	@httpPost
	global static void doPost() {
		// * CONVERT INVOICE BODY JSON TO CLASS DATA
		String invData = Restcontext.request.requestBody.toString();
		invData = invData.replaceAll('object', 'objectz');
		invData = invData.replaceAll('currency', 'currenyz');
		StripeInvoiceResponse stripeInvResp = (StripeInvoiceResponse) System.JSON.deserialize(
			invData,
			StripeInvoiceResponse.class
		);

		// * QUERY FOR CART
		Cart__c cart = [
			SELECT Id, Status__c, Amount_Paid__c, Total__c
			FROM Cart__c
			WHERE Stripe_Subscription_Id__c = :stripeInvResp.data.objectz.subscription
		];
		

        // * UPDATE CART INFO
		if (cart.Amount_Paid__c + (stripeInvResp.data.objectz.amount_paid / 100) >= cart.Total__c) {
            cart.Status__c = 'Paid';
		}

        // * CREATE INVOICE RECORD AGAIN CART
        Invoice__c inv = new Invoice__c(
            Cart__c = cart.Id,
            Amount__c = stripeInvResp.data.objectz.amount_paid / 100,
            Stripe_Invoice_Id__c = stripeInvResp.data.objectz.id,
			Invoice_PDF__c = stripeInvResp.data.objectz.hosted_invoice_url
        );

        upsert inv Stripe_Invoice_Id__c;
        update cart;
	}
}