force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Checkout Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Transaction Id</label>
    <length>84</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeCallbackClass.cls
@RestResource(UrlMapping='/Stripe')
global without sharing class StripeCallbackClass {
    
    @HttpPost
    global static void doPost() {
        String headers = JSON.serialize(RestContext.request.headers);
        String data = RestContext.request.requestBody.toString();
        System.debug(data);
        String formattedJSONString = data.replace('object', 'objectz');
        
        StripeResponse stripeResponse = (StripeResponse) JSON.deserialize(formattedJSONString, StripeResponse.class);

        System.debug(stripeResponse.data.objectz.id);

        Cart__c cart = [Select Id, Status__c from Cart__c where Stripe_Transaction_Id__c = :stripeResponse.data.objectz.id];

        cart.Status__c = 'Paid';

        update cart;
        
    }

    
}