force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Checkout Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Stripe_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Transaction_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Transaction Id</label>
    <length>84</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeCallbackClassTest.cls
@isTest
private class StripeCallbackClassTest {
	// @isTest
	// static void testStripeCallback() {
	//     // Create test data
	//     Cart__c testCart = new Cart__c();
	//     testCart.Stripe_Transaction_Id__c = 'testTransactionId';
	//     //testCart.Status__c = 'Unpaid';
	//     insert testCart;

	//     // Set up mock callout
	//     Test.setMock(HttpCalloutMock.class, new StripeCallbackMock());

	//     // Call the REST endpoint
	//     Test.startTest();
	//     RestRequest req = new RestRequest();
	//     RestResponse res = new RestResponse();
	//     req.requestURI = 'https://example.com/Stripe';
	//     req.httpMethod = 'POST';
	//     RestContext.request = req;
	//     RestContext.response = res;
	//     StripeCallbackClass.doPost();
	//     Test.stopTest();

	//     // Verify that the cart status is updated
	//     Cart__c updatedCart = [SELECT Status__c FROM Cart__c WHERE Id = :testCart.Id];
	//     System.assertEquals('Paid', updatedCart.Status__c,'Status is not paid');
	// }
}