force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <description>Shopping Cart used in the Experience Site</description>
    <label>Cart</label>
    <nameField>
        <displayFormat>CN-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Checkout Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <summarizedField>Cart_Product__c.Total__c</summarizedField>
    <summaryForeignKey>Cart_Product__c.Cart__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Cart_Product__c/Cart_Product__c.object-meta.xml
<CustomObject>
    <description>Junction object linking Carts to Products</description>
    <label>Cart Product</label>
    <nameField>
        <label>Cart Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cart Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Product__c/fields/Cart__c.field-meta.xml
<CustomField>
    <fullName>Cart__c</fullName>
    <label>Cart</label>
    <referenceTo>Cart__c</referenceTo>
    <relationshipLabel>Cart Products</relationshipLabel>
    <relationshipName>Cart_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Cart_Product__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Cart_Product__c/fields/Price_Cents__c.field-meta.xml
<CustomField>
    <fullName>Price_Cents__c</fullName>
    <formula>Total__c * 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price (Cents)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cart_Product__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CartService.cls
public with sharing class CartService {

	public static List<Cart__c> getUserCart(Id userId) {
		try {
			Id uCon = ContactService.getIdFromUser(userId);
			return [
				SELECT Id, Total__c
				FROM Cart__c
				WHERE Contact__c = :uCon AND Status__c = 'Open'
			];	
		} catch (QueryException e) {
			throw new AuraHandledException('No contact associated with the current user.');
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	public static Cart__c createUserCart(Id userId) {
		try {
			Cart__c cart = new Cart__c(
				Contact__c = ContactService.getIdFromUser(userId)
			);
			insert cart;

			return getUserCart(userId)[0];
		} catch (QueryException e) {
			throw new AuraHandledException('No contact associated with the current user.');
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
	}

	public static Cart__c getCart(Id cartId) {
		return [
			SELECT Id, Total__c, (SELECT Id, Name, Price__c, Quantity__c, Price_Cents__c, Total__c FROM Cart_Products__r)
			FROM Cart__c
			WHERE Id = :cartId
		];
	}
}