force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>CircEsteem Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CircEsteem Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <label>Payment Frequency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>In Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Program_Session__c/Program_Session__c.object-meta.xml
<CustomObject>
    <label>Program Session</label>
    <nameField>
        <label>Program Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Session__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Program Sessions</relationshipLabel>
    <relationshipName>Program_Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProgramService.cls
public with sharing class ProgramService {
    
    public static Program__c getProgramFromSession(String sessionId) {
        return [
            SELECT Id, Payment_Frequency__c, (SELECT Id, Start_Date__c, End_Date__c FROM Program_Sessions__r WHERE Id = :sessionId)
            FROM Program__c
            WHERE Id IN (SELECT Program__c FROM Program_Session__c WHERE Id = :sessionId)
            LIMIT 1
        ];
    }
}